spring.application.name=Tarea_Climalert

# Weather API
weather.api.key=${WEATHER_API_KEY}
weather.api.location=BUENOS_AIRES
weather.api.base-url=https://api.weatherapi.com/v1

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=santiasanchez@frba.utn.edu.ar
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true